/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdministrativeContacts: typeof import('./components/AdministrativeContacts.vue')['default']
    AuthInfo: typeof import('./components/AuthInfo.vue')['default']
    DetailItem: typeof import('./components/shared/DetailItem.vue')['default']
    DetailList: typeof import('./components/shared/DetailList.vue')['default']
    Events: typeof import('./components/Events.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    KeySet: typeof import('./components/KeySet.vue')['default']
    MySwitch: typeof import('./components/MySwitch.vue')['default']
    NsSet: typeof import('./components/NsSet.vue')['default']
    Owner: typeof import('./components/Owner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StateFlags: typeof import('./components/StateFlags.vue')['default']
  }
}
